apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: {{.Values.namespace}}
data:
  init.sql: |
    create database if not exists {{.Values.database.userdbName}};
    create database if not exists {{.Values.database.postdbName}};