apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/change-cause: "Deploying 0.2 version"
spec:
  replicas: {{.Values.services.posts.replicas}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image:  {{.Values.services.posts.image}}
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: MYSQL_DB_NAME
              value: postsdb
            - name: USERS_URL
              value: {{.Values.services.posts.usersUrl}}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
