apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None
  publishNotReadyAddresses: true


---
#SERVICE: users-service
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
#SERVICE: posts-service
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: http
      port: 8080
      targetPort: 8080