apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.services.users.replicas}}
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: {{.Values.services.users.image}}
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: MYSQL_DB_NAME
              value: usersdb
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 30
          volumeMounts:
            - name: mysql-init-script
              mountPath: /mysql-init-script
      volumes:
        - name: mysql-init-script
          configMap:
            name: mysql-init-script